services:
  - type: static_site
    name: abhishek-portfolio-client
    rootDir: .
    buildCommand: npm install && npm run build
    staticPublishPath: dist/portfolio-client
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: CLIENT_API_BASE_URL
        sync: false
